// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmGMWeMC0tJemqFL0AIdXKjguj31X3mQ',
    appId: '1:118812936354:web:1d1bf3a9c07d26232a6ffb',
    messagingSenderId: '118812936354',
    projectId: 'edulink-ca01f',
    authDomain: 'edulink-ca01f.firebaseapp.com',
    storageBucket: 'edulink-ca01f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDqdvxzLKS75uZv7Yqa6f5HCYAJOc3hk',
    appId: '1:118812936354:android:3114336fd65af34c2a6ffb',
    messagingSenderId: '118812936354',
    projectId: 'edulink-ca01f',
    storageBucket: 'edulink-ca01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcFpmbGpIwOHSphXZM1EB10RI0ioyRPo',
    appId: '1:118812936354:ios:9ecf6d30f1c087542a6ffb',
    messagingSenderId: '118812936354',
    projectId: 'edulink-ca01f',
    storageBucket: 'edulink-ca01f.firebasestorage.app',
    iosClientId: '118812936354-n7hnb84ame9jdgslhs3j12s6jrqh166d.apps.googleusercontent.com',
    iosBundleId: 'com.example.edulink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcFpmbGpIwOHSphXZM1EB10RI0ioyRPo',
    appId: '1:118812936354:ios:9ecf6d30f1c087542a6ffb',
    messagingSenderId: '118812936354',
    projectId: 'edulink-ca01f',
    storageBucket: 'edulink-ca01f.firebasestorage.app',
    iosClientId: '118812936354-n7hnb84ame9jdgslhs3j12s6jrqh166d.apps.googleusercontent.com',
    iosBundleId: 'com.example.edulink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmGMWeMC0tJemqFL0AIdXKjguj31X3mQ',
    appId: '1:118812936354:web:e73fc04ca8f7ba642a6ffb',
    messagingSenderId: '118812936354',
    projectId: 'edulink-ca01f',
    authDomain: 'edulink-ca01f.firebaseapp.com',
    storageBucket: 'edulink-ca01f.firebasestorage.app',
  );
}
